//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASliceOfColumbia.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceType
    {
        public DeviceType()
        {
            this.NearByRequests = new HashSet<NearByRequest1>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<NearByRequest1> NearByRequests { get; set; }
    }
}
