//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASliceOfColumbia.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NearByRequest1
    {
        public int ID { get; set; }
        public System.DateTime TimeOfRequest { get; set; }
        public int DeviceTypeID { get; set; }
        public System.Data.Entity.Spatial.DbGeography SpatialLocation { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
    }
}
