//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASliceOfColumbia.Web.Entities
{
    using System;
    
    public partial class REPORT_getRequestLocationsToClosestLocationSP_Result1
    {
        public System.DateTime TimeOfRequest { get; set; }
        public Nullable<double> ClosestLocation { get; set; }
        public byte[] SpatialData { get; set; }
    }
}
